### ISSUE TITLE
Problems to build Site 

### ISSUE THREAD

**Issue by ThomasGehPunkt** [techbarrack/terminal-hugo-theme#2]
Hello , 
i stucked building the site . Maybe you can help me.

when I start `hugo server - D` i get following errors

```
ERROR: 2024/04/24 12:23:24 template.go:472: template: /srv/../../themes/terminal/layouts/_default/baseof.html:2: function "site" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/authors.html:4: function "relLangURL" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/footer_content.html:3: function "now" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/head/css.html:1: function "resources" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/head/js.html:1: function "resources" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/head.html:9: function "site" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/pagination.html:11: function "time" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/tags.html:4: function "relLangURL" not defined
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/taxonomy.html:19: unexpected unclosed action in command
ERROR: 2024/04/24 12:23:24 template.go:472: template: theme/partials/third_party_js.html:5: unexpected "=" in operand
```
My config.toml looks like this:

baseurl = "http://....eu"
languageCode = "de-de"
title = "..."
theme = "terminal"

Is there a Problem with some function ?

**Comment by nayanseth** [comment]
1. Copy the hugo.yaml in themes/terminal to the root directory of your hugo site. And ensure that you delete the hugo.toml
2. Create a directory in the root folder of your hugo site: `mkdir -p layouts/partials/third_party_js`
3. Then run `hugo server` or `hugo server --buildDrafts --disableFastRender --gc --ignoreCache --noHTTPCache --forceSyncStatic --verbose -w`

I have updated the README.

**Comment by ThomasGehPunkt** [comment]
Hi , sorry to bother again.

Error is still:
`ERROR: 2024/04/25 12:28:40 template.go:472: template: /srv/enumlab25/enumath25/themes/terminal/layouts/_default/baseof.html:2: function "site" not defined`

but I realized that I run on an older version of hugo
`Hugo Static Site Generator v0.16 `
with package 
`hugo-0.16-2.el7.centos.x86_64`

because I can`t upgrade I want to ask if it possible to run your theme also with such an setting?

**Comment by nayanseth** [comment]
Can you try upgrading to latest version?

**Comment by ThomasGehPunkt** [comment]
If it not possible i have to try an other theme. But yours is cooler :-)

**Comment by nayanseth** [comment]
> But yours is cooler :-)

Glad to hear this

What version are you running?

**Comment by ThomasGehPunkt** [comment]
over hugo version got this
`Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T14:31:27+02:00`

package `hugo-0.16-2.el7.centos.x86_64`

**Comment by ThomasGehPunkt** [comment]
Hello , 
ok sorry for the inconvenience. I just realized that here they used a docker compose to build the sites with hugo . 
I think that why i couldn't realize your theme at the end. 

Please see the Problem as solved and thanks for your help and sorry for bothering
